import { Product } from '@/utils/types/product';

// Simple UUID generator for browser compatibility
const generateUUID = () => {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
};


export const TemplatedSash: Product[] = [
    {
      id: generateUUID(),
      name: 'Sash One',
      title: 'Sash One',
      description: '',
      image: '/images/templates/1.jpg',
      model_image: "/images/templates/2.jpg",
    //   confirm_image: sash1_actual,
      positioningLeft: {
        text: {
          top: '-1.5rem',
          left: '-5.5rem',
          height: '12rem',
          width: '5.4rem',
          lineHeight: '',
        },
        image: {
          top: '-8.5rem',
          left: '-4.5rem',
          height: '3rem',
          width: '3rem',
        },
      },
      positioningRight: {
        text: {
          top: '-1.8rem',
          left: '0.5rem',
          height: '12rem',
          width: '5.4rem',
          lineHeight: '',
        },
        image: {
          top: '-8.5rem',
          left: '2rem',
          height: '3rem',
          width: '3rem',
        },
      },
      otherYards: { small: 2, large: 3, extraLarge: 4, extraExtraLarge: 4 },
      myZoom: 0.6,
      price: 110,
      readyIn: 7,
      // sizeGuide: sash_guide,
      sizeOptions: [
        { label: 'S', value: 0.5 },
        { label: 'M', value: 1 },
        { label: 'L', value: 2 },
      ],
      extra_image_urls: [],
      sizes: [],
      colors: [],
      in_stock: true,
      scale: 1.2,

    },
    // {
    //   id: generateUUID(),
    //   name: 'Sash Two',
    //   title: 'Sash Two',
    //   description: '',
    //   image: '/images/templates/2.jpg',
    // //   model: sash2_actual,
    // //   confirm_image: sash2_actual,
    //   textColor: 'white',
    //   positioningLeft: {
    //     text: {
    //       top: '-2.2rem',
    //       left: '-2rem',
    //       height: '12rem',
    //       width: '4.4rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-8.5rem',
    //       left: '-1rem',
    //       height: '2.4rem',
    //       width: '2.4rem',
    //     },
    //   },
    //   positioningRight: {
    //     text: {
    //       top: '-3.2rem',
    //       left: '2.8rem',
    //       height: '12rem',
    //       width: '4.2rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-8.5rem',
    //       left: '4.3rem',
    //       height: '2.4rem',
    //       width: '2.4rem',
    //     },
    //   },
    //   otherYards: { small: 2, large: 3, extraLarge: 4, extraExtraLarge: 4 },
    //   myZoom: 0.6,
    //   price: 110,
    //   readyIn: 7,
    //   // sizeGuide: sash_guide,
    //   sizeOptions: [
    //     { label: 'S', value: 0.5 },
    //     { label: 'M', value: 1 },
    //     { label: 'L', value: 2 },
    //   ],
    //   extra_image_urls: [],
    //   sizes: [],
    //   colors: [],
    //   in_stock: true,
    //   scale: 1.2,

    // },
  
    {
      id: generateUUID(),
      name: 'Sash Three',
      title: 'Sash Three',
      description: '',
      image: '/images/templates/3.jpg',
      model_image: "/images/templates/4.jpg",
      // confirm_image: sash3_actual,
      positioningLeft: {
        text: {
          top: '-0.7rem',
          left: '-5.7rem',
          height: '13rem',
          width: '3.8rem',
          lineHeight: '',
        },
        image: {
          top: '-7rem',
          left: '-5.6rem',
          height: '3rem',
          width: '3rem',
        },
      },
      positioningRight: {
        text: {
          top: '-0.7rem',
          left: '-0.5rem',
          height: '12rem',
          width: '3.5rem',
          lineHeight: '',
        },
        image: {
          top: '-7rem',
          left: '0.3rem',
          height: '3rem',
          width: '3rem',
        },
      },
      otherYards: { small: 2, large: 3, extraLarge: 4, extraExtraLarge: 4 },
      myZoom: 0.6,
      price: 110,
      readyIn: 7,
      // sizeGuide: sash_guide,
      sizeOptions: [
        { label: 'S', value: 0.5 },
        { label: 'M', value: 1 },
        { label: 'L', value: 2 },
      ],
      extra_image_urls: [],
      sizes: [],
      colors: [],
      in_stock: true,
      scale: 1.2,

      },
  
    // {
    //   id: generateUUID(),
    //   name: 'Sash Four',
    //   title: 'Sash Four',
    //   description: '',
    //   image: '/images/templates/4.jpg',
    //   // model: sash4_actual,
    //   // confirm_image: sash4_actual,
    //   textColor: 'white',
    //   positioningLeft: {
    //     text: {
    //       top: '-1.2rem',
    //       left: '-4.6rem',
    //       height: '12rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-7rem',
    //       left: '-4rem',
    //       height: '2.4rem',
    //       width: '2.4rem',
    //     },
    //   },
    //   positioningRight: {
    //     text: {
    //       top: '-1.2rem',
    //       left: '0.3rem',
    //       height: '12rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-6.5rem',
    //       left: '0.7rem',
    //       height: '2.4rem',
    //       width: '2.4rem',
    //     },
    //   },
    //   otherYards: { small: 2, large: 3, extraLarge: 4, extraExtraLarge: 4 },
    //   myZoom: 0.6,
    //   price: 110,
    //   readyIn: 7,
    //   // sizeGuide: sash_guide,
    //   sizeOptions: [
    //     { label: 'S', value: 0.5 },
    //     { label: 'M', value: 1 },
    //     { label: 'L', value: 2 },
    //   ],
    //   extra_image_urls: [],
    //   sizes: [],
    //   colors: [],
    //   in_stock: true,
    //   scale: 1.2,

    // },
  
    {
      id: generateUUID(),
      name: 'Sash Five',
      title: 'Sash Five',
      description: '',
      image: '/images/templates/5.jpg',
      model_image: "/images/templates/6.jpg",
      // model: sash5_actual,
      // confirm_image: sash5_actual,
      positioningLeft: {
        text: {
          top: '-1rem',
          left: '-3.8rem',
          height: '9rem',
          width: '3.5rem',
          lineHeight: '2.4rem',
        },
        image: {
          top: '-5.8rem',
          left: '-3rem',
          height: '2rem',
          width: '2rem',
        },
      },
      positioningRight: {
        text: {
          top: '-0.5rem',
          left: '1.5rem',
          height: '9rem',
          width: '3.5rem',
          lineHeight: '2.4rem',
        },
        image: {
          top: '-5.4rem',
          left: '2.5rem',
          height: '1.7rem',
          width: '1.7rem',
        },
      },
      otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
      myZoom: 0.7,
      price: 110,
      readyIn: 7,
      // sizeGuide: sash_guide,
      sizeOptions: [
        { label: 'S', value: 0.5 },
        { label: 'M', value: 1 },
        { label: 'L', value: 2 },
      ],
      extra_image_urls: [],
      sizes: [],
      colors: [],
      in_stock: true,
      scale: 1.2,

    },
  
    // {
    //   id: generateUUID(),
    //   name: 'Sash Six',
    //   title: 'Sash Six',
    //   description: '',
    //   image: '/images/templates/6.jpg',
    //   // model: sash6_actual,
    //   // confirm_image: sash6_actual,
    //   textColor: 'white',
    //   positioningLeft: {
    //     text: {
    //       top: '-2.6rem',
    //       left: '-6.6rem',
    //       height: '12rem',
    //       width: '4.6rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-11.3rem',
    //       left: '-5.5rem',
    //       height: '2.8rem',
    //       width: '2.8rem',
    //     },
    //   },
    //   positioningRight: {
    //     text: {
    //       top: '-2.6rem',
    //       left: '-0.3rem',
    //       height: '12rem',
    //       width: '4.3rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-11.3rem',
    //       left: '0.5rem',
    //       height: '2.8rem',
    //       width: '2.8rem',
    //     },
    //   },
    //   otherYards: { small: 2, large: 4, extraLarge: 5, extraExtraLarge: 5 },
    //   myZoom: 0.65,
    //   price: 110,
    //   readyIn: 7,
    //   // sizeGuide: sash_guide,
    //   sizeOptions: [
    //     { label: 'S', value: 0.5 },
    //     { label: 'M', value: 1 },
    //     { label: 'L', value: 2 },
    //   ],
    //   extra_image_urls: [],
    //   sizes: [],
    //   colors: [],
    //   in_stock: true,
    //   scale: 1.2,

    // },
    {
      id: generateUUID(),
      name: 'Sash Seven',
      title: 'Sash Seven',
      description: '',
      image: '/images/templates/7.jpg',
      model_image: "/images/templates/8.jpg",
      // model: sash7_actual,
      // confirm_image: sash7_actual,
      positioningLeft: {
        text: {
          top: '-1.2rem',
          left: '-3.5rem',
          height: '8rem',
          width: '3.5rem',
          lineHeight: '',
        },
        image: {
          top: '-8rem',
          left: '-3.3rem',
          height: '2.5rem',
          width: '2.5rem',
        },
      },
      positioningRight: {
        text: {
          top: '-1.2rem',
          left: '0.2rem',
          height: '8rem',
          width: '3.5rem',
          lineHeight: '',
        },
        image: {
          top: '-8rem',
          left: '1rem',
          height: '2.3rem',
          width: '2.3rem',
        },
      },
      otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
      myZoom: 0.7,
      price: 110,
      readyIn: 7,
      // sizeGuide: sash_guide,
      sizeOptions: [
        { label: 'S', value: 0.5 },
        { label: 'M', value: 1 },
        { label: 'L', value: 2 },
      ],
      extra_image_urls: [],
      sizes: [],
      colors: [],
      in_stock: true,
      scale: 1.2,

    },
    // {
    //   id: generateUUID(),
    //   name: 'Sash Eight',
    //   title: 'Sash Eight',
    //   description: '',
    //   image: '/images/templates/8.jpg',
    //   // model: sash8_actual,
    //   // confirm_image: sash8_actual,
    //   positioningLeft: {
    //     text: {
    //       top: '-2rem',
    //       left: '-5rem',
    //       height: '9rem',
    //       width: '3.5rem',
    //       lineHeight: '2.4rem',
    //     },
    //     image: {
    //       top: '-9rem',
    //       left: '-4.5rem',
    //       height: '2.5rem',
    //       width: '2.5rem',
    //     },
    //   },
    //   positioningRight: {
    //     text: {
    //       top: '-2.6rem',
    //       left: '-0.6rem',
    //       height: '9rem',
    //       width: '3.5rem',
    //       lineHeight: '2.4rem',
    //     },
    //     image: {
    //       top: '-9.3rem',
    //       left: '0.4rem',
    //       height: '2.5rem',
    //       width: '2.5rem',
    //     },
    //   },
    //   otherYards: { small: 2, large: 3, extraLarge: 4, extraExtraLarge: 4 },
    //   myZoom: 0.65,
    //   price: 110,
    //   readyIn: 7,
    //   // sizeGuide: sash_guide,
    //   sizeOptions: [
    //     { label: 'S', value: 0.5 },
    //     { label: 'M', value: 1 },
    //     { label: 'L', value: 2 },
    //   ],
    //   extra_image_urls: [],
    //   sizes: [],
    //   colors: [],
    //   in_stock: true,
    //   scale: 1.2,

    // },
    {
      id: generateUUID(),
      name: 'Sash Nine',
      title: 'Sash Nine',
      description: '',
      image: '/images/templates/9.jpg',
      model_image: "/images/templates/10.jpg",
      // model: sash9_actual,
      // confirm_image: sash9_actual,
      positioningLeft: {
        text: {
          top: '-1.5rem',
          left: '-4.6rem',
          height: '10rem',
          width: '4rem',
          lineHeight: '',
        },
        image: {
          top: '-8.5rem',
          left: '-4rem',
          height: '2.5rem',
          width: '2.5rem',
        },
      },
      positioningRight: {
        text: {
          top: '-2.5rem',
          left: '1.2rem',
          height: '12rem',
          width: '4rem',
          lineHeight: '',
        },
        image: {
          top: '-9.2rem',
          left: '1.6rem',
          height: '2.5rem',
          width: '2.5rem',
        },
      },
      otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
      myZoom: 0.65,
      price: 110,
      readyIn: 7,
      // sizeGuide: sash_guide,
      sizeOptions: [
        { label: 'S', value: 0.5 },
        { label: 'M', value: 1 },
        { label: 'L', value: 2 },
      ],
      extra_image_urls: [],
      sizes: [],
      colors: [],
      in_stock: true,
      scale: 1.2,

    },
   
    // {
    //   id: generateUUID(),
    //   name: 'Sash Ten',
    //   title: 'Sash Ten',
    //   description: '',
    //   image: '/images/templates/10.jpg',
    //   // model: sash11_actual,
    //   // confirm_image: sash11_actual,
    //   textColor: 'white',
    //   positioningLeft: {
    //     text: {
    //       top: '-1rem',
    //       left: '-3.4rem',
    //       height: '8rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-7rem',
    //       left: '-2.8rem',
    //       height: '2rem',
    //       width: '2rem',
    //     },
    //   },
    //   positioningRight: {
    //     text: {
    //       top: '-1rem',
    //       left: '1rem',
    //       height: '8rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-7rem',
    //       left: '1.5rem',
    //       height: '2rem',
    //       width: '2rem',
    //     },
    //   },
    //   otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
    //   myZoom: 0.7,
    //   price: 110,
    //   readyIn: 7,
    //   // sizeGuide: sash_guide,
    //   sizeOptions: [
    //     { label: 'S', value: 0.5 },
    //     { label: 'M', value: 1 },
    //     { label: 'L', value: 2 },
    //   ],
    //   extra_image_urls: [],
    //   sizes: [],
    //   colors: [],
    //   in_stock: true,
    //   scale: 1.2,
    // },
    {
      id: generateUUID(),
      name: 'Sash Eleven',
      title: 'Sash Eleven',
      description: '',
      image: '/images/templates/11.jpg',
      model_image: "/images/templates/12.jpg",
      // model: sash12_actual,
      // confirm_image: sash12_actual,
      positioningLeft: {
        text: {
          top: '-0.8rem',
          left: '-3.4rem',
          height: '9rem',
          width: '3.4rem',
          lineHeight: '',
        },
        image: {
          top: '-6rem',
          left: '-2.7rem',
          height: '2.2rem',
          width: '2.2rem',
        },
      },
      positioningRight: {
        text: {
          top: '-0.8rem',
          left: '0.2rem',
          height: '9rem',
          width: '3.4rem',
          lineHeight: '',
        },
        image: {
          top: '-6rem',
          left: '1rem',
          height: '2.2rem',
          width: '2.2rem',
        },
      },
      otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
      myZoom: 0.7,
      price: 110,
      readyIn: 7,
      // sizeGuide: sash_guide,
      sizeOptions: [
        { label: 'S', value: 0.5 },
        { label: 'M', value: 1 },
        { label: 'L', value: 2 },
      ],
      extra_image_urls: [],
      sizes: [],
      colors: [],
      in_stock: true,
      scale: 1.2,

    },
    // {
    //   id: generateUUID(),
    //   name: 'Sash Twelve',
    //   title: 'Sash Twelve',
    //   description: '',
    //   image: '/images/templates/12.jpg',
    //   // model: sash13_actual,
    //   // confirm_image: sash13_actual,
    //   positioningLeft: {
    //     text: {
    //       top: '-2rem',
    //       left: '-4rem',
    //       height: '9rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-7rem',
    //       left: '-3.5rem',
    //       height: '2rem',
    //       width: '2rem',
    //     },
    //   },
    //   positioningRight: {
    //     text: {
    //       top: '-2rem',
    //       left: '0.5rem',
    //       height: '9rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-7rem',
    //       left: '1.5rem',
    //       height: '2rem',
    //       width: '2rem',
    //     },
    //   },
    //   otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
    //   myZoom: 0.75,
    //   price: 110,
    //   readyIn: 7,
    //   // sizeGuide: sash_guide,
    //   sizeOptions: [
    //     { label: 'S', value: 0.5 },
    //     { label: 'M', value: 1 },
    //     { label: 'L', value: 2 },
    //   ],
    //   extra_image_urls: [],
    //   sizes: [],
    //   colors: [],
    //   in_stock: true,
    // },
    {
      id: generateUUID(),
      name: 'Sash Thirteen',
      title: 'Sash Thirteen',
      description: '',
      image: '/images/templates/13.jpg',
      model_image: "/images/templates/14.jpg",
      // model: sash14_actual,
      // confirm_image: sash14_actual,
      positioningLeft: {
        text: {
          top: '-0.4rem',
          left: '-4.6rem',
          height: '9rem',
          width: '3.2rem',
          lineHeight: '',
        },
        image: {
          top: '-5.4rem',
          left: '-4rem',
          height: '2.2rem',
          width: '2.2rem',
        },
      },
      positioningRight: {
        text: {
          top: '-0.4rem',
          left: '1rem',
          height: '9rem',
          width: '3.2rem',
          lineHeight: '',
        },
        image: {
          top: '-5.3rem',
          left: '1rem',
          height: '2.2rem',
          width: '2.2rem',
        },
      },
      otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
      myZoom: 0.75,
      price: 110,
      readyIn: 7,
      // sizeGuide: sash_guide,
      sizeOptions: [
        { label: 'S', value: 0.5 },
        { label: 'M', value: 1 },
        { label: 'L', value: 2 },
      ],
      extra_image_urls: [],
      sizes: [],
      colors: [],
      in_stock: true,
      scale: 1.2,

    },
    // {
    //   id: generateUUID(),
    //   name: 'Sash Fourteen',
    //   title: 'Sash Fourteen',
    //   description: '',
    //   image: '/images/templates/14.jpg',
    // //   model: sash15_actual,
    // //   confirm_image: sash15_actual,
    //   textColor: 'white',
    //   positioningLeft: {
    //     text: {
    //       top: '-1.5rem',
    //       left: '-4.8rem',
    //       height: '9rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-8rem',
    //       left: '-4.5rem',
    //       height: '2rem',
    //       width: '2rem',
    //     },
    //   },
    //   positioningRight: {
    //     text: {
    //       top: '-1.5rem',
    //       left: '-0.7rem',
    //       height: '9rem',
    //       width: '3.5rem',
    //       lineHeight: '',
    //     },
    //     image: {
    //       top: '-8rem',
    //       left: '-0.3rem',
    //       height: '2rem',
    //       width: '2rem',
    //     },
    //   },
    //   otherYards: { small: 3, large: 4, extraLarge: 5, extraExtraLarge: 5 },
    //   myZoom: 0.8,
    //   price: 110,
    //   readyIn: 7,
    //   // sizeGuide: sash_guide,
    //   sizeOptions: [
    //     { label: 'S', value: 0.5 },
    //     { label: 'M', value: 1 },
    //     { label: 'L', value: 2 },
    //   ],
    //   extra_image_urls: [],
    //   sizes: [],
    //   colors: [],
    //   in_stock: true,
    //   scale: 1.2,

    // },
    
  ];